# Site settings
layout: splash
title: "Welcome to My Portfolio"
header:
  image: /assets/images/header-image.svg
  caption: "An SVG illustration showcasing data analysis."
  overlay_color: "#333"
  overlay_filter: "0.5"
  actions:
    - label: "View Projects"
      url: "/projects/"
      class: "btn--primary"
email: "usamah.abdulazeez@gmail.com"
description: "Data scientist showcasing projects and skills."
url: "https://usamahabdulazeez.github.io"
baseurl: "" # or "/repository-name"
github_username: UsamahAbdulazeez
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
timezone: "America/Chicago"
paginate: 3

# Author information
author:
  name: "Usamah Abdulazeez"
  avatar: "/assets/images/chicago_tree.jpg"
  bio: "Data scientist by degree, problem-solver by nature."
  email: "usamah.abdulazeez@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/uabdulazeez"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UsamahAbdulazeez"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/uabdulazeez"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UsamahAbdulazeez"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
